### ISSUE TITLE
Direct test of ResNet50 with pytorch official released weights can achieve ~24% top1 accuracy

### ISSUE THREAD

**Issue by BannyStone** [HaohanWang/ImageNet-Sketch#6]
Has anyone got similar results?

**Comment by HaohanWang** [comment]
Have you checked these two links?
https://www.kaggle.com/rwightman/generalization-to-imagenet-sketch 
https://github.com/rwightman/pytorch-image-models/blob/master/results/results-sketch.csv

**Comment by BannyStone** [comment]
Got it. So it is normal to achieve ~24% with resnet50. Thank you for your hint.
