### ISSUE TITLE
Add dataset to Hugging Face Hub

### ISSUE THREAD

**Issue by nateraw** [HaohanWang/ImageNet-Sketch#7]
Hey there, I'd really like to add this dataset to the [Hugging Face `datasets`](https://github.com/huggingface/datasets) package. Unfortunately, Google Drive links have rate limits, so we would rather the data is coming from somewhere else.

I've unofficially uploaded the dataset to the Hugging Face Hub [here](https://huggingface.co/datasets/nateraw/imagenet-sketch-data) for now so I can include it in [my PR](https://github.com/huggingface/datasets/pull/4301) to add this to `datasets`. What would be great is if you did the same under your own account so we could make it a bit more official 🤗 . I can even actually transfer my repo's ownership to you, so all I'd need is your account name.

If you have any issue with us uploading the data to the Hub, please let me know too and I'll take it down!

**Comment by nateraw** [comment]
Update - the dataset now lives here: https://huggingface.co/datasets/imagenet_sketch

and can be loaded using the `datasets` library like this:

```python
from datasets import load_dataset

dataset = load_dataset("imagenet_sketch")
```

**Comment by HaohanWang** [comment]
Great! Thank you very much.
